server:
  port: 8080

spring:
  application:
    name: gateway-service
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger/index.html
    disable-swagger-default-url: true
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    health:
      show-details: never
resilience4j:
  circuitbreaker:
    instances:
      default-circuit-breaker:
        failure-rate-threshold: 30
        wait-duration-in-open-state: 10s
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10
        sliding-window-type: count_based