spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${POSTGRESQL_PORT}/${POSTGRES_COMMENT_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  liquibase:
    change-log: classpath:db.changelog/db.changelog-patches.xml
    enabled: true