spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/image_service
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db.changelog/db.changelog-patches.xml
    enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE